"""Post-generation validation of a rendered output directory.

Runs structural checks (no unresolved tokens, real solution/project files,
valid JSON/XML/Bash) plus the generated project's own suite_metadata check
and scaffold test suite, and — when `dotnet` is available — its portable
preflight and unit tests. This is intentionally the single place that
decides whether a generation attempt is safe to hand to the user.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

from .model import ProjectParams
from .render import ROOT_NAMESPACE_PATH_SENTINEL

# Every `python3`/`bash` subprocess below runs *inside* `output_dir`, which
# is promoted verbatim into the delivered project. Without this, importing
# a local module (e.g. `tests/scaffold/test_scaffold.py`) writes a
# `__pycache__/*.pyc` that ships as part of the generated project — the
# same "local files incorporated into every generated project" problem
# the template manifest closes for `template/` itself, just at the
# staging-execution boundary instead of the render boundary.
NO_BYTECODE_ENV = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}

# Bootstrapper-owned implementation identity that must never survive into a
# generated project's own code, metadata, *or path* (a filename/directory
# name leaks identity exactly as badly as file content -- e.g. a binary
# `ValheimSuite.Common.dll`, whose bytes are legitimately never decoded,
# still leaks through its name). Deliberately narrow: legitimate
# provenance prose such as "generated by ValheimSuite Bootstrap." (no dot
# after ValheimSuite, no namespace/using/.sln/.csproj/.dll context) must
# keep passing validation.
IDENTITY_LEAK_PATTERNS = [
    re.compile(r"\bnamespace\s+ValheimSuite\b"),
    re.compile(r"\busing\s+ValheimSuite\b"),
    re.compile(r"\bValheimSuite\.(?:Common|ServerCore|Client|Shared)\b"),
    re.compile(r"\bValheimSuite\.sln\b"),
    re.compile(r"\bValheimSuite\.[A-Za-z][A-Za-z.]*\.(?:csproj|dll)\b"),
]
GUID_LEAK_PATTERN = re.compile(r"\bcom\.example\.valheimsuite\b")
# Matches an actual MSBuild <Import> element, not prose/comments that merely mention the path.
SUITE_GENERATED_IMPORT_RE = re.compile(r'<Import\s+Project="[^"]*build/Suite\.Generated\.props"')


@dataclass
class ValidationResult:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


def _text_files(root: Path):
    for f in root.rglob("*"):
        if f.is_file():
            try:
                yield f, f.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue


def _append_identity_leak_errors(value: str, location: str, r: ValidationResult) -> None:
    for pattern in IDENTITY_LEAK_PATTERNS:
        if pattern.search(value):
            r.errors.append(f"leaked bootstrapper implementation identity {location}: {pattern.pattern}")
    if GUID_LEAK_PATTERN.search(value):
        r.errors.append(f"leftover default placeholder plugin GUID root {location}")


def validate_generated(output_dir: Path, params: ProjectParams) -> ValidationResult:
    r = ValidationResult()

    # Path validation first: every directory and file beneath `output_dir`,
    # regardless of whether its content decodes as UTF-8 text. A path has
    # no legitimate escaped/template brace syntax: reject either raw
    # doubled-brace delimiter outright. A path sentinel or identity leak can also
    # show up in a relative path itself (a binary `ValheimSuite.Common.dll`,
    # a `ValheimSuite.ServerCore/` directory) independently of anything the
    # content-based checks below can ever see.
    for f in sorted(output_dir.rglob("*")):
        rel = f.relative_to(output_dir)
        rel_str = str(rel)
        if "{{" in rel_str or "}}" in rel_str:
            r.errors.append(f"unresolved template brace delimiter in path: {rel}")
        if ROOT_NAMESPACE_PATH_SENTINEL in rel_str:
            r.errors.append(f"unresolved path token in {rel}")
        _append_identity_leak_errors(rel_str, f"in path {rel}", r)

    # Content validation: decodable UTF-8 text only. Binary content is
    # intentionally never decoded/scanned here -- its *path* was already
    # fully validated above, which is what actually catches a binary
    # filename leak; treating arbitrary binary bytes as text would be
    # false confidence, not a stronger check. Generated text has no
    # legitimate doubled-brace delimiters either.
    for f, text in _text_files(output_dir):
        rel = f.relative_to(output_dir)
        if "{{" in text or "}}" in text:
            r.errors.append(f"unresolved template token in {rel}: doubled-brace delimiter")
        if ROOT_NAMESPACE_PATH_SENTINEL in text:
            r.errors.append(f"unresolved path token in {rel} content")
        if "TODO-before-public-release" in text:
            r.errors.append(f"leftover TODO placeholder in {rel}")
        _append_identity_leak_errors(text, f"in {rel}", r)

    config_path = output_dir / "suite.config.json"
    if not config_path.is_file():
        r.errors.append("missing suite.config.json")
        return r
    cfg = json.loads(config_path.read_text(encoding="utf-8"))

    sln = output_dir / f"{cfg['rootNamespace']}.sln"
    if not sln.is_file():
        r.errors.append(f"missing solution file: {sln.name}")
    else:
        sln_text = sln.read_text(encoding="utf-8")
        for project in cfg["projects"]:
            csproj = output_dir / "src" / project / f"{project}.csproj"
            if not csproj.is_file():
                r.errors.append(f"missing project file: {csproj}")
            if f"src\\{project}\\{project}.csproj" not in sln_text:
                r.errors.append(f"solution does not reference {project}")

    for f in output_dir.rglob("*.json"):
        try:
            json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            r.errors.append(f"invalid JSON {f.relative_to(output_dir)}: {exc}")

    for f in list(output_dir.rglob("*.csproj")) + list(output_dir.rglob("*.props")):
        try:
            ET.parse(f)
        except ET.ParseError as exc:
            r.errors.append(f"invalid MSBuild XML {f.relative_to(output_dir)}: {exc}")

    for f in output_dir.rglob("*.sh"):
        proc = subprocess.run(["bash", "-n", str(f)], text=True, capture_output=True)
        if proc.returncode != 0:
            r.errors.append(f"bash syntax error in {f.relative_to(output_dir)}: {proc.stdout}{proc.stderr}")

    generated_props_importers = [
        name
        for name in ("Directory.Build.props", "Directory.Packages.props")
        if (output_dir / name).is_file() and SUITE_GENERATED_IMPORT_RE.search((output_dir / name).read_text(encoding="utf-8"))
    ]
    if len(generated_props_importers) > 1:
        r.errors.append(
            "build/Suite.Generated.props is imported by more than one MSBuild-auto-imported props file "
            f"({', '.join(generated_props_importers)}); MSBuild only evaluates the first import and warns "
            "MSB4011 on the rest"
        )
    packages = cfg["packages"]
    scopes = {name: item["scope"] for name, item in cfg["projects"].items()}
    server = {packages["commonModule"], *packages["serverModules"]}
    client = {
        packages["commonModule"],
        *packages["requiredClientModules"],
        *packages["optionalClientModules"],
        *packages["clientOnlyModules"],
    }
    if any(scopes[m] == "clientOnly" for m in server):
        r.errors.append("server package set contains a clientOnly project")
    if any(scopes[m] == "serverOnly" for m in client):
        r.errors.append("client package set contains a serverOnly project")

    proc = subprocess.run(
        ["python3", "scripts/suite_metadata.py", "check"],
        cwd=output_dir,
        env=NO_BYTECODE_ENV,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        r.errors.append(f"suite_metadata check failed: {proc.stdout}{proc.stderr}")

    proc = subprocess.run(
        ["python3", "-m", "unittest", "discover", "-s", "tests/scaffold", "-p", "test_*.py"],
        cwd=output_dir,
        env=NO_BYTECODE_ENV,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        r.errors.append(f"generated scaffold tests failed: {proc.stdout}{proc.stderr}")

    if shutil.which("dotnet") is None:
        r.skipped.append("dotnet not installed: skipped scripts/preflight.sh --portable and scripts/test.sh")
    else:
        proc = subprocess.run(
            ["bash", "scripts/preflight.sh", "--portable", "--json"],
            cwd=output_dir,
            env=NO_BYTECODE_ENV,
            text=True,
            capture_output=True,
        )
        if proc.returncode != 0:
            r.errors.append(f"portable preflight failed: {proc.stdout}{proc.stderr}")
        proc = subprocess.run(
            ["bash", "scripts/test.sh"], cwd=output_dir, env=NO_BYTECODE_ENV, text=True, capture_output=True
        )
        if proc.returncode != 0:
            r.errors.append(f"scripts/test.sh failed: {proc.stdout}{proc.stderr}")

    return r
