// <auto-generated />
namespace ValheimSuite.Common;

public static class SuiteConstants
{
    public const string Name = "ValheimSuite";
    public const string Version = "0.1.0";
    public const string GuidRoot = "com.example.valheimsuite";
}
