import json
import tempfile
import unittest
from pathlib import Path

from bootstrap.model import build_model, solution_text, suite_config_dict
from bootstrap.validate_generated import validate_generated
from tests.fixtures._helpers import make_params


def _write_minimal_valid_project(output_dir: Path, params) -> None:
    model = build_model(params)
    (output_dir / "suite.config.json").write_text(
        json.dumps(suite_config_dict(model), indent=2) + "\n", encoding="utf-8"
    )
    (output_dir / f"{params.root_namespace}.sln").write_text(solution_text(model), encoding="utf-8")
    for m in model.modules:
        project_dir = output_dir / "src" / m.project_name
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / f"{m.project_name}.csproj").write_text("<Project />", encoding="utf-8")


class IdentityLeakDetectionTests(unittest.TestCase):
    def test_leaked_bootstrapper_namespace_fails_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "Leaked.cs").write_text("namespace ValheimSuite.Foo;\n", encoding="utf-8")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(any("Leaked.cs" in e for e in result.errors), result.errors)

    def test_leaked_default_guid_root_fails_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "stray.json").write_text('{"guid": "com.example.valheimsuite.server"}', encoding="utf-8")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(any("stray.json" in e for e in result.errors), result.errors)

    def test_legitimate_bootstrapper_prose_does_not_fail_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "PROVENANCE.md").write_text(
            "This project was generated by HeimForge.\n", encoding="utf-8"
        )

        result = validate_generated(output_dir, params)

        identity_errors = [e for e in result.errors if "PROVENANCE.md" in e]
        self.assertEqual([], identity_errors)

    def test_provenance_exception_does_not_widen_to_nearby_namespace_leak(self):
        """Allowing "generated by HeimForge." prose must not
        also let a real implementation-namespace leak pass elsewhere in
        the same generation."""
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "PROVENANCE.md").write_text(
            "This project was generated by HeimForge.\n", encoding="utf-8"
        )
        (output_dir / "Leaked.cs").write_text("namespace ValheimSuite.ServerCore;\n", encoding="utf-8")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertEqual([], [e for e in result.errors if "PROVENANCE.md" in e])
        self.assertTrue(any("Leaked.cs" in e for e in result.errors), result.errors)

    def test_leaked_identity_in_text_filename_fails_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "ValheimSuite.ServerCore.cs").write_text("// stray file\n", encoding="utf-8")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(
            any("ValheimSuite.ServerCore.cs" in e and "path" in e for e in result.errors), result.errors
        )

    def test_leaked_identity_in_binary_filename_fails_validation(self):
        """A binary `ValheimSuite.Common.dll` must fail on its filename
        alone -- its bytes are never decoded/scanned, but the path is."""
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "ValheimSuite.Common.dll").write_bytes(b"\x4d\x5a\x00\x01\xff\xfe not real PE bytes")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(
            any("ValheimSuite.Common.dll" in e and "path" in e for e in result.errors), result.errors
        )

    def test_leaked_identity_in_directory_name_fails_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        leaked_dir = output_dir / "ValheimSuite.ServerCore"
        leaked_dir.mkdir()
        (leaked_dir / "empty.bin").write_bytes(b"\x00\x01\xff\xfe")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(
            any("ValheimSuite.ServerCore" in e and "path" in e for e in result.errors), result.errors
        )

    def test_normal_binary_filename_and_content_does_not_fail_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "icon.png").write_bytes(b"\x89PNG\r\n\x1a\nnot a real png but binary\xff\xfe")

        result = validate_generated(output_dir, params)

        icon_errors = [e for e in result.errors if "icon.png" in e]
        self.assertEqual([], icon_errors)


if __name__ == "__main__":
    unittest.main()
