import json
import tempfile
import unittest
from pathlib import Path

from bootstrap.model import build_model, solution_text, suite_config_dict
from bootstrap.validate_generated import validate_generated
from tests.fixtures._helpers import make_params


def _write_minimal_valid_project(output_dir: Path, params) -> None:
    model = build_model(params)
    (output_dir / "suite.config.json").write_text(
        json.dumps(suite_config_dict(model), indent=2) + "\n", encoding="utf-8"
    )
    (output_dir / f"{params.root_namespace}.sln").write_text(solution_text(model), encoding="utf-8")
    for m in model.modules:
        project_dir = output_dir / "src" / m.project_name
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / f"{m.project_name}.csproj").write_text("<Project />", encoding="utf-8")


class IdentityLeakDetectionTests(unittest.TestCase):
    def test_leaked_bootstrapper_namespace_fails_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "Leaked.cs").write_text("namespace ValheimSuite.Foo;\n", encoding="utf-8")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(any("Leaked.cs" in e for e in result.errors), result.errors)

    def test_leaked_default_guid_root_fails_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "stray.json").write_text('{"guid": "com.example.valheimsuite.server"}', encoding="utf-8")

        result = validate_generated(output_dir, params)

        self.assertFalse(result.ok)
        self.assertTrue(any("stray.json" in e for e in result.errors), result.errors)

    def test_legitimate_bootstrapper_prose_does_not_fail_validation(self):
        params = make_params()
        output_dir = Path(tempfile.mkdtemp(prefix="valheimsuite-bootstrap-fixture-"))
        _write_minimal_valid_project(output_dir, params)
        (output_dir / "PROVENANCE.md").write_text(
            "This project was generated by ValheimSuite Bootstrap.\n", encoding="utf-8"
        )

        result = validate_generated(output_dir, params)

        identity_errors = [e for e in result.errors if "PROVENANCE.md" in e]
        self.assertEqual([], identity_errors)


if __name__ == "__main__":
    unittest.main()
