from __future__ import annotations

import json
import os
import re
import subprocess
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


class ScaffoldTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.cfg = json.loads((ROOT / "suite.config.json").read_text(encoding="utf-8"))

    def test_metadata_is_synchronized(self):
        result = subprocess.run(
            ["python3", "scripts/suite_metadata.py", "check"],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        self.assertEqual(0, result.returncode, result.stdout)

    def test_all_configured_projects_exist_and_solution_mentions_them(self):
        sln = (ROOT / "ValheimSuite.sln").read_text(encoding="utf-8")
        for project in self.cfg["projects"]:
            csproj = ROOT / "src" / project / f"{project}.csproj"
            self.assertTrue(csproj.is_file(), project)
            self.assertIn(f"src\\{project}\\{project}.csproj", sln)

    def test_deployment_classification_excludes_wrong_side(self):
        p = self.cfg["packages"]
        server = {p["commonModule"], *p["serverModules"]}
        client = {p["commonModule"], *p["requiredClientModules"], *p["optionalClientModules"], *p["clientOnlyModules"]}
        scopes = {name: item["scope"] for name, item in self.cfg["projects"].items()}
        self.assertFalse(any(scopes[m] == "clientOnly" for m in server))
        self.assertFalse(any(scopes[m] == "serverOnly" for m in client))
        self.assertIn("ValheimSuite.ServerCore", server)
        self.assertNotIn("ValheimSuite.ServerCore", client)
        self.assertIn("ValheimSuite.Client", client)
        self.assertNotIn("ValheimSuite.Client", server)

    def test_bash_scripts_parse_and_are_executable(self):
        for script in sorted((ROOT / "scripts").glob("*.sh")):
            self.assertTrue(os.access(script, os.X_OK), f"not executable: {script.name}")
            result = subprocess.run(["bash", "-n", str(script)], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            self.assertEqual(0, result.returncode, f"{script.name}: {result.stdout}")

    def test_local_sensitive_configuration_is_ignored(self):
        gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
        for required in ("Environment.props", ".valheim/dev.json", "artifacts/", "**/bin/", "**/obj/"):
            self.assertIn(required, gitignore)
        self.assertFalse((ROOT / "Environment.props").exists())
        self.assertFalse((ROOT / ".valheim" / "dev.json").exists())

    def test_generated_constants_are_the_only_suite_constants_source(self):
        generated = ROOT / "src" / "ValheimSuite.Common" / "SuiteConstants.Generated.cs"
        self.assertTrue(generated.is_file())
        self.assertFalse((ROOT / "src" / "ValheimSuite.Common" / "SuiteConstants.cs").exists())
        text = generated.read_text(encoding="utf-8")
        self.assertIn("<auto-generated", text)
        self.assertIn(self.cfg["pluginGuidRoot"], text)

    def test_net48_projects_use_cross_platform_reference_assemblies(self):
        for project, item in self.cfg["projects"].items():
            if item["targetFramework"] != "net48":
                continue
            text = (ROOT / "src" / project / f"{project}.csproj").read_text(encoding="utf-8")
            self.assertIn('PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies"', text)

    def test_plugin_compatibility_boundaries_remain_as_designed(self):
        server = (ROOT / "src/ValheimSuite.ServerCore/Plugin.cs").read_text(encoding="utf-8")
        client = (ROOT / "src/ValheimSuite.Client/Plugin.cs").read_text(encoding="utf-8")
        shared = (ROOT / "src/ValheimSuite.Shared.Diagnostics/Plugin.cs").read_text(encoding="utf-8")
        self.assertIn("CompatibilityLevel.NotEnforced, VersionStrictness.None", server)
        self.assertIn("CompatibilityLevel.NotEnforced, VersionStrictness.None", client)
        self.assertIn("CompatibilityLevel.VersionCheckOnly, VersionStrictness.Minor", shared)

    def test_packaging_is_real_not_placeholder(self):
        text = (ROOT / "scripts/package.sh").read_text(encoding="utf-8")
        self.assertNotIn("Packaging scaffold only", text)
        self.assertTrue((ROOT / "scripts/package.py").is_file())

    def test_no_arbitrary_log_command_in_dev_schema(self):
        example = json.loads((ROOT / ".valheim/dev.json.example").read_text(encoding="utf-8"))
        self.assertNotIn("serverLogCommand", example)


if __name__ == "__main__":
    unittest.main()
